name: westwind_server
description: Starting point for a Serverpod server.
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  serverpod: 2.3.1
  serverpod_auth_server: 2.3.1
  dotenv: ^4.2.0
  logging: ^1.3.0
  mailer: ^6.4.1


dev_dependencies:
  lints: ^3.0.0
