
INSERT into rate_table ("rateType", "rateReason","rate") 
VALUES 
 ('standard','single',86)
,('standard','share',56)
,('standard','triple',56)
,('standard','stuff',44)
,('standard','double',112)
,('standard','gohome',0)
,('standard','other',0)
,('ironhand','single',76)
,('ironhand','share',52.5)
,('ironhand','double',105)
,('ironhand','triple',52.5)
,('ironhand','gohome',0)
,('ironhand','other',0)

,('ensign','single',86)
,('ensign','share',56)
,('ensign','double',112)
,('ensign','triple',56)
,('ensign','gohome',0)
,('ensign','other',0)

,('horizon','single',86)
,('horizon','share',56)
,('horizon','double',112)
,('horizon','triple',56)
,('clear','single',86)
,('clear','share',56)
,('clear','double',112)
,('clear','triple',56)
,('clear','gohome',0)
,('clear','other',0)
,('global','single',76)
,('global','share',52.5)
,('global','double',105)
,('global','gohome',0)
,('global','other',0)
,('dartstar','single',86)
,('dartstar','share',56)
,('dartstar','double',112)
,('online','single',74)
,('online','double',88)
,('stuff','single',44)
,('stuff','double',56);
