INSERT INTO room ("id","roomNumber","roomType","roomStatus","bedType","isAvailable","isSmoke","isBigTV","isNewAC","isNewBed","isBigRefergrator") 
VALUES 

     (101,'Rm101','single','empty','queen',true,false,true,true,true,true)    
    ,(102,'Rm102','double','empty','queen',true,false,true,true,true,true)
    ,(103,'Rm103','single','empty','queen',true,false,true,true,true,true)
    ,(104,'Rm104','doulbe','empty','queen',true,false,true,true,true,true)
    ,(105,'Rm105','single','empty','queen',true,false,true,true,true,true)
    ,(106,'Rm106','doulbe','empty','queen',true,false,true,true,true,true)
    ,(107,'Rm107','single','empty','queen',true,false,true,true,true,true)
    ,(108,'Rm108','doulbe','empty','queen',true,false,true,true,true,true)
    ,(110,'Rm110','doulbe','empty','queen',false,false,true,true,true,true)
    ,(111,'Rm111','single','empty','queen',false,false,true,true,true,true)
    ,(112,'Rm112','suit','empty','queen',false,false,true,true,true,true)
     ,(201,'Rm101','single','empty','queen',true,false,true,true,true,true)    
    ,(202,'Rm102','double','empty','queen',true,false,true,true,true,true)
    ,(203,'Rm103','single','empty','queen',true,false,true,true,true,true)
    ,(204,'Rm104','doulbe','empty','queen',true,false,true,true,true,true)
    ,(205,'Rm105','single','empty','queen',true,false,true,true,true,true)
    ,(206,'Rm106','doulbe','empty','queen',true,false,true,true,true,true)
    ,(207,'Rm107','single','empty','queen',true,false,true,true,true,true)
    ,(208,'Rm108','doulbe','empty','queen',true,false,true,true,true,true)
    ,(209,'Rm110','doulbe','empty','queen',false,false,true,true,true,true)
    ,(210,'Rm111','single','empty','queen',false,false,true,true,true,true)
    ,(212,'Rm112','suit','empty','queen',false,false,true,true,true,true);