# Use this file to store passwords to services that your server you use. When
# the server starts, the passwords will be automatically loaded and can be
# accessed from the `session.passwords` field. If you don't have access to a
# session object, passwords can also be accessed from
# `Serverpod.instance.passwords`. You can provide different passwords for
# different run configurations. If you want the same password for any
# configuration used, place it under `shared`.
#
# Note that this file should not be under version control. Store it in a safe
# place.

# Save passwords used across all configurations here.
shared:
  mySharedPassword: 'my password'

# These are passwords used when running the server locally in development mode
development:
  database: '8lozzN3S344jkh5UlLJ7eQ358zh_EFfT'
  redis: 'F3omk0sbA5zf-vZZ48aOiR_48tsj6laa'


  # The service secret is used to communicate between servers and to access the
  # service protocol.
  serviceSecret: 'Ig8ylwWKacPS6TccQs6EJEkZvpTE_SM3'

# Passwords used in your staging environment if you use one. The default setup
# use a password for Redis.
staging:
  database: '6yK2CyLbkItQ9qnePCweyWxPeunQR8GR'
  serviceSecret: '6esjeez-12mWARoqGmZGpFZXNUiZsE26'

# Passwords used in production mode.
production:
  database: 'ii0x-Hqj4h4bshTCDkdTcSbmw7mKFDGs'
  serviceSecret: '6Wpr-biXVcjJo22vaLaHu3eZJs6jLWov'
